### ISSUE TITLE
Ignore SSL section configuration settings when Astra secure connect bundle is specified

### ISSUE THREAD

**Issue by yabinmeng** [datastax/pulsar-sink#10]
Right now, if we provide **cloud.secureConnectBundle** setting in the configuration file (in order to connect to Astra), The connector creation will actually fail (although the "puslar-admin" command says successfully) by complaining that SSL settings are not allowed while using secure connect bundle, even for something like below. It has to be complete blank for every configuration parameter under **ssl** section.

``` 
    ssl:
    **provider: None**
    hostnameValidation:
    keystore:
      password:
      path:
    openssl:
      keyCertChain:
      privateKey:
    truststore:
      password:
      path:
    cipherSuites:
```

I think there are probably 2 improvements that we can make here:

1). We should let the connector ignore SSL settings (and probably Auth settings as well) completely if the secure connect bundle file is provided.
2) We should have better error message returned back to the command line if the connector actually fails.
